export const Sponsors = [
    "AOK Neckar-Alb",
    "Apotheke am Markt",
    "Bäckerei Leins e.K.",
    "Bien-Zenker GmbH",
    "Brillinger GmbH & CO. KG",
    "Der Elektromann (Kai Dirks und Alexander Freund GbR)",
    "DGM Kommunikation",
    "Edel GmbH & Co. KG",
    "Elektro Sanfilippo",
    "Erath Fensterbau",
    "ETAPART AG  ",
    "Feral GmbH",
    "Fliesenfachgeschäft Markus Neu",
    "Gauss Ingenieurtechnik GmbH",
    "Gebr. Stumpp Bauunternehmung GmbH & Co. KG",
    "Gustav Elsberger Fuhrunternehmen GmbH",
    "H+B Bauprojekte GmbH",
    "Hecon Abrechnungssysteme GmbH",
    "Immobilen Merz GmbH",
    "Zahnarzt Johann Peter Schwarze",
    "Kaya Sanitärtechnik",
    "Karosserie-Baur GmbH",
    "KEMPA - uhlsport GmbH",
    "Kreissparkasse Tübingen",
    "Krokodil Gastronomiebetriebe GmbH",
    "Kronenbrauerei Alfred Schimpf GmbH",
    "Liedtke Autowaschcenter",
    "Micki Sport Handels GmbH",
    "Modehaus Weippert & Co. OHG",
    "Norz Optik",
    "Pizza + Pasta Rottenburg",
    "Physio-MED med. Kooperationsgemeinschaft GbR",
    "Pulvermüller - Christoph Unger GmbH & Co. KG",
    "Rino - Eiscafé by Rino Rottenburg",
    "Römer-Apotheke",
    "RWT REUTLINGER WIRTSCHAFTSTREUHAND GMBH",
    "Scheck Bad und Heizung",
    "Schreinerei Volk",
    "Schloss Weitenburg",
    "Scirotec GmbH",
    "Sportpark 1861 TV Rottenburg",
    "Stadtwerke Rottenburg am Neckar GmbH",
    "Tierärztliche Hausapotheken GmbH",
    "TransPak AG",
    "VOELKER & Partner Rechtsanwälte Wirtschaftsprüfer Steuerberater",
    "Wachendorfer GbR Glaserei & Fensterbau",
    "Winfried Riegger GmbH",
    "Winghofer Medicum Klinik GmbH",
    "Zahnarzt Dr. Kocher",
    "Stuckateur Steger GmbH",
    "Volksbank Herrenberg-Nagold-Rottenburg",
    "afri Cola",
    "Brunnenstube",
    "Druckerei Maier GmbH",
    "Elektro Betz",
    "Flammer Bauunternehmung",
    "kesslerundkern",
    "KLAUS FAHRNER WOHNKONZEPT GMBH",
    "Picks Raus Bloemsaat GmbH",
    "Wizemann Computerservice",
    "Sitzi",
]